name: build sdl2

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: sdl2
      run: sudo apt update; sudo apt install libsdl2-dev libsdl2-image-dev libsdl2-gfx-dev
    - name: make
      run: make
    - name: install mingw
      run: sudo apt install g++-mingw-w64
    - name: install sfml for mingw
      run: cd /usr/x86_64-w64-mingw32; sudo wget https://www.libsdl.org/release/SDL2-devel-2.0.20-mingw.tar.gz; sudo tar -xf SDL2-devel-2.0.20-mingw.tar.gz;
    - name: windows
      run: make windows-linux
      
    - uses: actions/upload-artifact@v2
      with:
        name: ubuntu
        path: |
          bin/
          assets
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
